// Generated by gencpp from file de_msgs/QueryNextPosRequest.msg
// DO NOT EDIT!


#ifndef DE_MSGS_MESSAGE_QUERYNEXTPOSREQUEST_H
#define DE_MSGS_MESSAGE_QUERYNEXTPOSREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace de_msgs
{
template <class ContainerAllocator>
struct QueryNextPosRequest_
{
  typedef QueryNextPosRequest_<ContainerAllocator> Type;

  QueryNextPosRequest_()
    : demo(false)  {
    }
  QueryNextPosRequest_(const ContainerAllocator& _alloc)
    : demo(false)  {
  (void)_alloc;
    }



   typedef uint8_t _demo_type;
  _demo_type demo;





  typedef boost::shared_ptr< ::de_msgs::QueryNextPosRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::de_msgs::QueryNextPosRequest_<ContainerAllocator> const> ConstPtr;

}; // struct QueryNextPosRequest_

typedef ::de_msgs::QueryNextPosRequest_<std::allocator<void> > QueryNextPosRequest;

typedef boost::shared_ptr< ::de_msgs::QueryNextPosRequest > QueryNextPosRequestPtr;
typedef boost::shared_ptr< ::de_msgs::QueryNextPosRequest const> QueryNextPosRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::de_msgs::QueryNextPosRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::de_msgs::QueryNextPosRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::de_msgs::QueryNextPosRequest_<ContainerAllocator1> & lhs, const ::de_msgs::QueryNextPosRequest_<ContainerAllocator2> & rhs)
{
  return lhs.demo == rhs.demo;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::de_msgs::QueryNextPosRequest_<ContainerAllocator1> & lhs, const ::de_msgs::QueryNextPosRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace de_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::de_msgs::QueryNextPosRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::de_msgs::QueryNextPosRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::de_msgs::QueryNextPosRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::de_msgs::QueryNextPosRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::de_msgs::QueryNextPosRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::de_msgs::QueryNextPosRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::de_msgs::QueryNextPosRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f73ec22bee61d6074a81a65d05b9a709";
  }

  static const char* value(const ::de_msgs::QueryNextPosRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf73ec22bee61d607ULL;
  static const uint64_t static_value2 = 0x4a81a65d05b9a709ULL;
};

template<class ContainerAllocator>
struct DataType< ::de_msgs::QueryNextPosRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "de_msgs/QueryNextPosRequest";
  }

  static const char* value(const ::de_msgs::QueryNextPosRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::de_msgs::QueryNextPosRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool demo\n"
;
  }

  static const char* value(const ::de_msgs::QueryNextPosRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::de_msgs::QueryNextPosRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.demo);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct QueryNextPosRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::de_msgs::QueryNextPosRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::de_msgs::QueryNextPosRequest_<ContainerAllocator>& v)
  {
    s << indent << "demo: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.demo);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DE_MSGS_MESSAGE_QUERYNEXTPOSREQUEST_H
