// Generated by gencpp from file de_msgs/QueryBrickLocRequest.msg
// DO NOT EDIT!


#ifndef DE_MSGS_MESSAGE_QUERYBRICKLOCREQUEST_H
#define DE_MSGS_MESSAGE_QUERYBRICKLOCREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace de_msgs
{
template <class ContainerAllocator>
struct QueryBrickLocRequest_
{
  typedef QueryBrickLocRequest_<ContainerAllocator> Type;

  QueryBrickLocRequest_()
    : num(0.0)  {
    }
  QueryBrickLocRequest_(const ContainerAllocator& _alloc)
    : num(0.0)  {
  (void)_alloc;
    }



   typedef double _num_type;
  _num_type num;





  typedef boost::shared_ptr< ::de_msgs::QueryBrickLocRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::de_msgs::QueryBrickLocRequest_<ContainerAllocator> const> ConstPtr;

}; // struct QueryBrickLocRequest_

typedef ::de_msgs::QueryBrickLocRequest_<std::allocator<void> > QueryBrickLocRequest;

typedef boost::shared_ptr< ::de_msgs::QueryBrickLocRequest > QueryBrickLocRequestPtr;
typedef boost::shared_ptr< ::de_msgs::QueryBrickLocRequest const> QueryBrickLocRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::de_msgs::QueryBrickLocRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::de_msgs::QueryBrickLocRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::de_msgs::QueryBrickLocRequest_<ContainerAllocator1> & lhs, const ::de_msgs::QueryBrickLocRequest_<ContainerAllocator2> & rhs)
{
  return lhs.num == rhs.num;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::de_msgs::QueryBrickLocRequest_<ContainerAllocator1> & lhs, const ::de_msgs::QueryBrickLocRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace de_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::de_msgs::QueryBrickLocRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::de_msgs::QueryBrickLocRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::de_msgs::QueryBrickLocRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::de_msgs::QueryBrickLocRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::de_msgs::QueryBrickLocRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::de_msgs::QueryBrickLocRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::de_msgs::QueryBrickLocRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f942a3e0cbd340847b2a0e5b31a783fe";
  }

  static const char* value(const ::de_msgs::QueryBrickLocRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf942a3e0cbd34084ULL;
  static const uint64_t static_value2 = 0x7b2a0e5b31a783feULL;
};

template<class ContainerAllocator>
struct DataType< ::de_msgs::QueryBrickLocRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "de_msgs/QueryBrickLocRequest";
  }

  static const char* value(const ::de_msgs::QueryBrickLocRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::de_msgs::QueryBrickLocRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 num\n"
;
  }

  static const char* value(const ::de_msgs::QueryBrickLocRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::de_msgs::QueryBrickLocRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.num);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct QueryBrickLocRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::de_msgs::QueryBrickLocRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::de_msgs::QueryBrickLocRequest_<ContainerAllocator>& v)
  {
    s << indent << "num: ";
    Printer<double>::stream(s, indent + "  ", v.num);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DE_MSGS_MESSAGE_QUERYBRICKLOCREQUEST_H
