(cl:in-package de_msgs-srv)
(cl:export '(H_X-VAL
          H_X
          H_Y-VAL
          H_Y
          H_Z-VAL
          H_Z
          H_WX-VAL
          H_WX
          H_WY-VAL
          H_WY
          H_WZ-VAL
          H_WZ
          B_X-VAL
          B_X
          B_Y-VAL
          B_Y
          B_Z-VAL
          B_Z
          B_WX-VAL
          B_WX
          B_WY-VAL
          B_WY
          B_WZ-VAL
          B_WZ
          G_X-VAL
          G_X
          G_Y-VAL
          G_Y
          G_Z-VAL
          G_Z
          G_WX-VAL
          G_WX
          G_WY-VAL
          G_WY
          G_WZ-VAL
          G_WZ
          SUCCESS-VAL
          SUCCESS
))