(cl:defpackage de_msgs-srv
  (:use )
  (:export
   "MOVEARM"
   "<MOVEARM-REQUEST>"
   "MOVEARM-REQUEST"
   "<MOVEARM-RESPONSE>"
   "MOVEARM-RESPONSE"
   "QUERYBRICKLOC"
   "<QUERYBRICKLOC-REQUEST>"
   "QUERYBRICKLOC-REQUEST"
   "<QUERYBRICKLOC-RESPONSE>"
   "QUERYBRICKLOC-RESPONSE"
   "QUERYNEXTPOS"
   "<QUERYNEXTPOS-REQUEST>"
   "QUERYNEXTPOS-REQUEST"
   "<QUERYNEXTPOS-RESPONSE>"
   "QUERYNEXTPOS-RESPONSE"
   "QUERYPPBRICK"
   "<QUERYPPBRICK-REQUEST>"
   "QUERYPPBRICK-REQUEST"
   "<QUERYPPBRICK-RESPONSE>"
   "QUERYPPBRICK-RESPONSE"
  ))

