// Generated by gencpp from file arm_master/MoveArmRequest.msg
// DO NOT EDIT!


#ifndef ARM_MASTER_MESSAGE_MOVEARMREQUEST_H
#define ARM_MASTER_MESSAGE_MOVEARMREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace arm_master
{
template <class ContainerAllocator>
struct MoveArmRequest_
{
  typedef MoveArmRequest_<ContainerAllocator> Type;

  MoveArmRequest_()
    : x(0.0)
    , y(0.0)
    , z(0.0)
    , rot_x(0.0)
    , rot_y(0.0)
    , rot_z(0.0)  {
    }
  MoveArmRequest_(const ContainerAllocator& _alloc)
    : x(0.0)
    , y(0.0)
    , z(0.0)
    , rot_x(0.0)
    , rot_y(0.0)
    , rot_z(0.0)  {
  (void)_alloc;
    }



   typedef double _x_type;
  _x_type x;

   typedef double _y_type;
  _y_type y;

   typedef double _z_type;
  _z_type z;

   typedef double _rot_x_type;
  _rot_x_type rot_x;

   typedef double _rot_y_type;
  _rot_y_type rot_y;

   typedef double _rot_z_type;
  _rot_z_type rot_z;





  typedef boost::shared_ptr< ::arm_master::MoveArmRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::arm_master::MoveArmRequest_<ContainerAllocator> const> ConstPtr;

}; // struct MoveArmRequest_

typedef ::arm_master::MoveArmRequest_<std::allocator<void> > MoveArmRequest;

typedef boost::shared_ptr< ::arm_master::MoveArmRequest > MoveArmRequestPtr;
typedef boost::shared_ptr< ::arm_master::MoveArmRequest const> MoveArmRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::arm_master::MoveArmRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::arm_master::MoveArmRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::arm_master::MoveArmRequest_<ContainerAllocator1> & lhs, const ::arm_master::MoveArmRequest_<ContainerAllocator2> & rhs)
{
  return lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.z == rhs.z &&
    lhs.rot_x == rhs.rot_x &&
    lhs.rot_y == rhs.rot_y &&
    lhs.rot_z == rhs.rot_z;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::arm_master::MoveArmRequest_<ContainerAllocator1> & lhs, const ::arm_master::MoveArmRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace arm_master

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::arm_master::MoveArmRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::arm_master::MoveArmRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::arm_master::MoveArmRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::arm_master::MoveArmRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::arm_master::MoveArmRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::arm_master::MoveArmRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::arm_master::MoveArmRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c6173d79f90cee4dca8ef07b705ba82f";
  }

  static const char* value(const ::arm_master::MoveArmRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc6173d79f90cee4dULL;
  static const uint64_t static_value2 = 0xca8ef07b705ba82fULL;
};

template<class ContainerAllocator>
struct DataType< ::arm_master::MoveArmRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "arm_master/MoveArmRequest";
  }

  static const char* value(const ::arm_master::MoveArmRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::arm_master::MoveArmRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 rot_x\n"
"float64 rot_y\n"
"float64 rot_z\n"
"\n"
;
  }

  static const char* value(const ::arm_master::MoveArmRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::arm_master::MoveArmRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.z);
      stream.next(m.rot_x);
      stream.next(m.rot_y);
      stream.next(m.rot_z);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MoveArmRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::arm_master::MoveArmRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::arm_master::MoveArmRequest_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<double>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<double>::stream(s, indent + "  ", v.y);
    s << indent << "z: ";
    Printer<double>::stream(s, indent + "  ", v.z);
    s << indent << "rot_x: ";
    Printer<double>::stream(s, indent + "  ", v.rot_x);
    s << indent << "rot_y: ";
    Printer<double>::stream(s, indent + "  ", v.rot_y);
    s << indent << "rot_z: ";
    Printer<double>::stream(s, indent + "  ", v.rot_z);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ARM_MASTER_MESSAGE_MOVEARMREQUEST_H
